[[SDL2_ttf]]
arch = "aarch64"
git-tree-sha1 = "b9952b2b7db6584090a27bd1cd1877d18229a5cf"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "cedd3dd6302328c4d0a745d9e58296faea740178f29d09a56e8353d1788d2efa"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.aarch64-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "aarch64"
git-tree-sha1 = "a866082b07ae764d2d4e246aec02b4d967267278"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "3cb5eb54fbc7a6b05a6efc6f3fe7cede0b8c92eea8c3e8dc7c64c51eba6745c0"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.aarch64-linux-musl.tar.gz"
[[SDL2_ttf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c4e16ba7f8b3c10bd07dbadb9b37c83036ded613"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "621750b8488d521625c29528aeaf91b62cb51844e61b70503e52d6824c2d17fd"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.armv7l-linux-gnueabihf.tar.gz"
[[SDL2_ttf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae92a749adf172e871cc98a73854b990bbe9d239"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "cc7e0720e45324c297bf84ed4301646b7756460b222677c67eddffd35895df69"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.armv7l-linux-musleabihf.tar.gz"
[[SDL2_ttf]]
arch = "i686"
git-tree-sha1 = "f12f09fe0cf1c017cf65c280042de04ec097aa75"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "608971cf7ea48e1c6f0245763dfcf1707a748d4b82d2e3a676f2158108459284"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.i686-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "i686"
git-tree-sha1 = "3d434a81f0c5f61422f31f578c66d09f623f9ae5"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "5949c21c00c2a497e27380a811121c0e207afd08404c8082458f5715156e3ed7"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.i686-linux-musl.tar.gz"
[[SDL2_ttf]]
arch = "i686"
git-tree-sha1 = "adea5dfd9b881dd52b6a6f32d60a9272d4ccfe23"
os = "windows"

    [[SDL2_ttf.download]]
    sha256 = "6401037c64688d3c84099c0d00ac335235c259638f77c58b0b3dd6e2e31eeb07"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.i686-w64-mingw32.tar.gz"
[[SDL2_ttf]]
arch = "powerpc64le"
git-tree-sha1 = "6d54eb98c4ae9d07275d2796ccd2ed490cff13e4"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "853e713fcc34cfd2c5f69b3f0369302cb43684585097cf6463a378592922be30"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.powerpc64le-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "cd55913a7c7547643a4361244907ff5c19eecf6e"
os = "macos"

    [[SDL2_ttf.download]]
    sha256 = "e8acc5cb0aacfb3c9e60cd707d56a50527b0962a021c2a2bd2e51bb6f9c056b9"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.x86_64-apple-darwin.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "9f270eb59a7dbcc620d97eca06805bef49be1f4d"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "5bc99b9ff0ca896dc421638e2cdb3bc281dfa9ac44e013c1f42504f1769dab0c"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.x86_64-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "bed9ebad7426ad3fd145010cd4c2e43a2d98b85e"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "e8ad368ac9381ba0b34eedb8f90bbf0926b9fe18c1e196f693d66d9c0ce43f7d"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.x86_64-linux-musl.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "a33c3f49b16777b4a641e720d6d294f4fd3c0a65"
os = "freebsd"

    [[SDL2_ttf.download]]
    sha256 = "ade93ffe9d7e315b47ee6a38f0253b5e402956e0d8776a6dce3cf66c3e989d53"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.x86_64-unknown-freebsd.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "8d0a818db52810385a96309b62eb0f8c468710f6"
os = "windows"

    [[SDL2_ttf.download]]
    sha256 = "14979def934e6512aa46bf3f6341992dd6514cab0c9bb9bda427897b4933eb09"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.16+0/SDL2_ttf.v2.0.16.x86_64-w64-mingw32.tar.gz"
