[[SDL2_ttf]]
arch = "aarch64"
git-tree-sha1 = "2e834dd34b43b4fba7c49453317d60515f237530"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "14d69270f7aeb5f9f8859b44867da40a0960b81b28a25bf61fccc48c67b0ccc1"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.aarch64-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "aarch64"
git-tree-sha1 = "50217472a60d7bf50776225ee196ea8e067ae09f"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "0b1dd5962af2b70d3fcae499828411c073a91a77664747b2b2a0f12c698de00a"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.aarch64-linux-musl.tar.gz"
[[SDL2_ttf]]
arch = "armv7l"
git-tree-sha1 = "83a8d78a08ae84bc05c1618e2e8ffa7133785bb8"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "fb19b3f9fe7aecc7a6bf3115028a364687f30d3bba0af6bc7f905c607a96ab1a"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.armv7l-linux-gnueabihf.tar.gz"
[[SDL2_ttf]]
arch = "armv7l"
git-tree-sha1 = "2970d160323f29c4d7087fc55ab9d57c0ef4734a"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "49a8e0f0cb21b49c523526ee2b0ee1d63dc896624335a42f2b09ec58495f03b3"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.armv7l-linux-musleabihf.tar.gz"
[[SDL2_ttf]]
arch = "i686"
git-tree-sha1 = "525aaa198efd35695ba9d85f8e4ece82ed4c6116"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "34b2ac82e21e76e92715324c4a39f4d9e16fc2ae12467bee9e4984cb9dd11dea"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.i686-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "i686"
git-tree-sha1 = "d425acf851a4369b02ffba86680299f3a3da839d"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "5808a3580f55b36ed4647a088b9e216d9c089cfee19e06196fb10a6922ab0ff2"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.i686-linux-musl.tar.gz"
[[SDL2_ttf]]
arch = "i686"
git-tree-sha1 = "b8da94b683403d5c8876b05030998f71caca154c"
os = "windows"

    [[SDL2_ttf.download]]
    sha256 = "480a0406afd2ccf2d472de02dabc92aa340b0cc2f833357bf8c09be4f4bfa854"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.i686-w64-mingw32.tar.gz"
[[SDL2_ttf]]
arch = "powerpc64le"
git-tree-sha1 = "02e1a224c51fe527ecb5e824ff8b73a7eb0ef7e9"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "b05f825b1e73f7670d0253cecc70afefd2b2b041132db30632d56fb7d9287e88"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.powerpc64le-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "b2c1c8e2d3d86c763e3b55512f69898f1808c084"
os = "macos"

    [[SDL2_ttf.download]]
    sha256 = "39f2fe8612aa45658734cff361cd484593b7d6de12c23a32dd7b48cd91757add"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.x86_64-apple-darwin14.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "fc9de42e729d829feae81ee6016b368f81e809e0"
libc = "glibc"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "8da5b88be47b734f9586999f51bccd3780210379e79e931ddc57087692138097"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.x86_64-linux-gnu.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "948d0734fba321d1333ea42af82d10d46d7def47"
libc = "musl"
os = "linux"

    [[SDL2_ttf.download]]
    sha256 = "65669a8fd3bc123279b7a19977769cd4f4c41645487af60b69ed7575b0f6130a"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.x86_64-linux-musl.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "4c15816e619062fcc96f6129c8d6ffcee6b689c3"
os = "freebsd"

    [[SDL2_ttf.download]]
    sha256 = "2a9a900227df038030a00580d348f0daffc35c88b94594e228bbd64052352c76"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.x86_64-unknown-freebsd11.1.tar.gz"
[[SDL2_ttf]]
arch = "x86_64"
git-tree-sha1 = "e28051a37342c00c26408720fa245e7b1a54ea46"
os = "windows"

    [[SDL2_ttf.download]]
    sha256 = "8e9739acf118f3a8b8e00e185be41be0811b75ed6db49ef503b6bcf186dfc1e7"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_ttf_jll.jl/releases/download/SDL2_ttf-v2.0.15+1/SDL2_ttf.v2.0.15.x86_64-w64-mingw32.tar.gz"
